---
- name: Set_fact | Disto release version
  ansible.builtin.set_fact:
    _rel: |-
      {%- if ansible_distribution_major_version in ['8', '9'] -%}
      8
      {%- elif ansible_distribution_major_version == '7' -%}
      7
      {%- endif -%}
    _base_url: "{{ keydb_packages.redhat.pkg_base_url }}"
    _arch: "{{ ansible_architecture }}"

- name: Set_fact | KeyDB package file name
  ansible.builtin.set_fact:
    _pkg_name: "keydb-{{ keydb_version }}-1.el{{ _rel }}.{{ _arch }}.rpm"

- name: Set_fact | KeyDB package URL
  ansible.builtin.set_fact:
    _pkg_url: "{{ _base_url }}{{ _rel }}/{{ _arch }}/keydb_all_versions/{{ _pkg_name }}"

- name: Yum_key | KeyDB package gpg
  ansible.builtin.rpm_key:
    state: present
    key: "{{ keydb_packages.redhat.rpm_key }}"

- name: Get_url | Download KeyDB package
  ansible.builtin.get_url:
    url: "{{ _pkg_url }}"
    dest: "/tmp/{{ _pkg_name }}"
    mode: "0755"

- name: Yum | Install KeyDB remote package
  ansible.builtin.yum:
    name: "/tmp/{{ _pkg_name }}"
    state: present
    allow_downgrade: true
