---
- name: Manage KeyDB Changes # noqa: no-changed-when
  ansible.builtin.command: /bin/true
  notify:
    - Notify On Changes
    - Restart KeyDB

- name: Restart KeyDB
  ansible.builtin.systemd:
    name: keydb
    daemon_reload: true
    enabled: true
    state: restarted
  when: keydb_restart_on_changes is truthy

- name: Notify On Changes
  ansible.builtin.debug:
    msg: "Confuration has been changed. Manual restart required!"
  when: keydb_restart_on_changes is falsy

- name: Reload Systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: THP Service
  ansible.builtin.systemd:
    name: disable-transparent-huge-pages
    daemon_reload: "{{ keydb_thp_enable }}"
    enabled: "{{ keydb_thp_enable }}"
    state: "{{ keydb_thp_enable | ternary('started', 'stopped') }}"
